"""
Django settings for firstDjangoProject project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p&k6x5@_zpiz6d48a3-e58o*yfwqijrtv0pr!+of@(4ixx642s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['.vercel.app']
ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app', '.now.sh', 'localhost','*']


# AUTH_USER_MODEL='accounts.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
# Adding our own apps below->
EXTERNAL_APPS=[
    'accounts',
    'home',
    'recipeProject',
]

INSTALLED_APPS+=EXTERNAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'firstDjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'firstDjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        
        # Upper is sqlite , below is mysql and below that mongodb using djongo connection

        # 'NAME': BASE_DIR / 'db.sqlite3',
        # 'ENGINE': 'django.db.backends.mysql', 
        # 'NAME': 'django',
        # 'USER': 'root',
        # 'PASSWORD': 'Pt.98283',
        # 'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        # 'PORT': '3306',

        'ENGINE': 'django.db.backends.postgresql', 
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'oFxlTxWvMyWsSGodiqoTvItVuutHSbtU',
        'HOST': 'viaduct.proxy.rlwy.net',   # Or an IP Address that your DB is hosted on
        'PORT': '43258',

        # 'ENGINE': 'djongo',
        # 'NAME': 'Chat-app',
        # 'CLIENT': {
        #     'host': 'mongodb+srv://priyanshutiwari83182:Pt.98283@cluster0.37e0trd.mongodb.net/Chat-app?retryWrites=true&w=majority',
        #     'username': 'priyanshutiwari83182',
        #     'password': 'Pt.98283',
        # }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/' //this line is default rest written for django static files setup...
import os
# STATIC_ROOT="staticfiles" 
STATIC_URL="/static/"     # for html/css files...
STATIC_ROOT=os.path.join(BASE_DIR,"staticfiles") # for admin...

STATICFILES_DIR={
    os.path.join(BASE_DIR,"public/static")
}

MEDIA_ROOT=os.path.join(BASE_DIR,"public/static") # for media files...
MEDIA_URL="/media/"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Code below for sending email->

EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER=""
EMAIL_HOST_PASSWORD=""